name: Upsert Migration

on:
  # pull_request_review:
  #   types: [submitted]
  pull_request:
    branches:
      - main
    paths:
      - "**/*.up.sql"

jobs:
  bytebase-upsert-migration:
    runs-on: ubuntu-latest
    env:
      BYTEBASE_URL: "https://demo.bytebase.com"
      BYTEBASE_SERVICE_ACCOUNT: "ci@service.bytebase.com"
      PROJECT: "project-sample"
      DATABASE: "instances/test-sample-instance/databases/hr_test"
      ISSUE_TITLE: "[${{ github.repository }}#${{ github.event.pull_request.number }}] ${{ github.event.pull_request.title }}"
      DESCRIPTION: "Triggered by ${{ github.event.repository.html_url }}/pull/${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}"
    name: Upsert Migration
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Bytebase
        id: login
        uses: bytebase/login-action@0.0.2
        with:
          bytebase-url: ${{ env.BYTEBASE_URL }}
          service-key: ${{ env.BYTEBASE_SERVICE_ACCOUNT }}
          service-secret: "bbs_iqysPHMqhNpG4rQ5SFEJ" # Please use secrets for sensitive data in production.
      - name: Upsert issue
        id: upsert
        uses: ./.github/actions/upsert-issue
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "**/*.up.sql"
          url: ${{ env.BYTEBASE_URL }}
          token: ${{ steps.login.outputs.token }}
          headers: '{"Accept-Encoding": "deflate, gzip"}'
          project-id: ${{ env.PROJECT }}
          database: ${{ env.DATABASE }}
          title: ${{ env.ISSUE_TITLE }}
          description: ${{ env.DESCRIPTION }}
