name: SQL Review

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.sql"

jobs:
  bytebase-sql-review:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    env:
      BYTEBASE_URL: "https://demo.bytebase.com"
      BYTEBASE_SERVICE_ACCOUNT: "ci@service.bytebase.com"
      PROJECT: "projects/project-sample"
      DATABASE: "instances/test-sample-instance/databases/hr_test"
    name: SQL Review
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Bytebase
        id: login
        uses: bytebase/login-action@0.0.2
        with:
          bytebase-url: ${{ env.BYTEBASE_URL }}
          service-key: ${{ env.BYTEBASE_SERVICE_ACCOUNT }}
          service-secret: "bbs_iqysPHMqhNpG4rQ5SFEJ" # Please use secrets for sensitive data in production.
      - name: Review
        id: review
        uses: bytebase/create-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_STEP_DEBUG: true # Enable debug logs
        with:
          url: ${{ env.BYTEBASE_URL }}
          token: ${{ steps.login.outputs.token }}
          file-pattern: "migrations/*.sql"
          # fail the action if release checks report any error.
          check-release: "FAIL_ON_ERROR"
          project: ${{ env.PROJECT }}
          targets: ${{ env.DATABASE }}
          validate-only: true
